<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7736f502-89d2-426d-b5d2-c5cfe48a5c5e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VendorAccessGovernance.Application\VendorAccessGovernance.Application.csproj" />
    <ProjectReference Include="..\VendorAccessGovernance.Infrastructure\VendorAccessGovernance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
